apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: minikube-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: minikube-deployment
  minReplicas: 2  # Mínimo de réplicas
  maxReplicas: 10  # Máximo de réplicas
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50